# -*- coding: utf-8 -*-
"""Programação orientada a objetos em python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q2mO4aZGJdmmNHkxxCuWYkgSfVzXgA10

Programação orientada a objetos em python

Iniciante:

1) O que é programação orientada a objetos (POO) e por que ela é importante?

2) Quais são os quatro princípios fundamentais da programação orientada a objetos?

3) O que é uma classe em Python e como você pode definir uma?

4) O que é um objeto em Python e como você pode criar um?

5) Qual é a diferença entre uma classe e um objeto em Python?

Intermediário:

6) O que são atributos de classe e atributos de instância em Python?

7) Como você pode acessar os atributos de um objeto em Python?

8) O que são métodos de classe e métodos de instância em Python?

9) Como você pode chamar um método em um objeto em Python?

10) O que é herança em Python e como você pode usá-la para criar subclasses?

Avançado:

11) O que é encapsulamento e como ele é implementado em Python?

12) O que são métodos estáticos e como eles são definidos em uma classe Python?

13) O que é polimorfismo e como ele é implementado em Python?

14) Como você pode usar sobrecarga de operadores em Python para criar

15) comportamentos personalizados para operadores embutidos?

16) O que são classes abstratas e como elas são definidas em Python usando o módulo abc?
"""

2) Quais são os quatro princípios fundamentais da programação orientada a objetos?

3) O que é uma classe em Python e como você pode definir uma?

4) O que é um objeto em Python e como você pode criar um?

5) Qual é a diferença entre uma classe e um objeto em Python?

6) O que são atributos de classe e atributos de instância em Python?

7) Como você pode acessar os atributos de um objeto em Python?

8) O que são métodos de classe e métodos de instância em Python?

9) Como você pode chamar um método em um objeto em Python?

10) O que é herança em Python e como você pode usá-la para criar subclasses?

11) O que é encapsulamento e como ele é implementado em Python?

12) O que são métodos estáticos e como eles são definidos em uma classe Python?

13) O que é polimorfismo e como ele é implementado em Python?

14) Como você pode usar sobrecarga de operadores em Python para criar

15) comportamentos personalizados para operadores embutidos?

16) O que são classes abstratas e como elas são definidas em Python usando o módulo abc?