# -*- coding: utf-8 -*-
"""Programação funcional em Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZhCLoDy_12_sTKGzHdvmZJYTIPIzcpTS

Programação funcional em Python

Nível Inicial:

1) O que é uma função lambda em Python e qual é sua sintaxe básica?

2) Como você pode usar uma função lambda para definir uma função simples em Python?

3) Qual é a função da função map() em Python e como você a utiliza?

4) Como você pode aplicar uma função a todos os elementos de uma lista usando a função map()?

5) O que é a função filter() em Python e como você a usa para filtrar elementos de uma lista?

Nível Intermediário:

6) Como você pode usar a função filter() em conjunto com uma função lambda para filtrar elementos de uma lista em Python?

7) Qual é a função da função reduce() em Python e como você a utiliza?

8) Como você pode usar a função reduce() para combinar os elementos de uma lista em um único resultado?

9) O que é a função zip() em Python e como ela se relaciona com a programação funcional?

10) Como você pode usar a função zip() em conjunto com a função map() ou filter() para operações mais avançadas?

Nível Avançado:

11) O que são funções de ordem superior em Python e como elas estão relacionadas à programação funcional?

12) Como você pode usar a função map() e a função filter() de forma aninhada em Python?

13) O que são iteradores e geradores em Python e como eles se relacionam com a programação funcional?

14) Como você pode criar uma função geradora que produz uma sequência infinita de valores em Python?

15) O que é programação funcional reativa e como ela pode ser aplicada em Python?
"""

1) O que é uma função lambda em Python e qual é sua sintaxe básica?

2) Como você pode usar uma função lambda para definir uma função simples em Python?

3) Qual é a função da função map() em Python e como você a utiliza?

4) Como você pode aplicar uma função a todos os elementos de uma lista usando a função map()?

5) O que é a função filter() em Python e como você a usa para filtrar elementos de uma lista?

6) Como você pode usar a função filter() em conjunto com uma função lambda para filtrar elementos de uma lista em Python?

7) Qual é a função da função reduce() em Python e como você a utiliza?

8) Como você pode usar a função reduce() para combinar os elementos de uma lista em um único resultado?

9) O que é a função zip() em Python e como ela se relaciona com a programação funcional?

10) Como você pode usar a função zip() em conjunto com a função map() ou filter() para operações mais avançadas?

11) O que são funções de ordem superior em Python e como elas estão relacionadas à programação funcional?

12) Como você pode usar a função map() e a função filter() de forma aninhada em Python?

13) O que são iteradores e geradores em Python e como eles se relacionam com a programação funcional?

14) Como você pode criar uma função geradora que produz uma sequência infinita de valores em Python?

15) O que é programação funcional reativa e como ela pode ser aplicada em Python?