# -*- coding: utf-8 -*-
"""While - estruturas de repetições python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Z9nR9bTbYod4z92pwNGApnwdICZP2Te

Nível Inicial:

1) O que é a instrução while em Python e para que ela é usada?

2) Como você pode escrever uma estrutura de repetição simples usando a instrução while?

3) Qual é a diferença entre a instrução while e a instrução for em Python?

4) Como você pode evitar loops infinitos ao usar a instrução while?

Nível Intermediário:

5) O que são expressões booleanas e como elas são usadas com a instrução while?

6) Como você pode usar uma instrução while para iterar sobre uma lista em Python?

7) O que é uma condição de parada e como você pode usá-la com a instrução while?

8) Como você pode usar a instrução break para sair de um loop while prematuramente em Python?

Nível Avançado:

9) O que é a instrução else em uma instrução while em Python e em que situações ela é útil?

10) Como você pode usar a instrução continue para pular uma iteração do loop while em Python?

11) O que são loops aninhados e como você pode usá-los com a instrução while?

12) Como você pode usar a instrução while para implementar lógica de repetição em um programa mais complexo?
"""

1) O que é a instrução while em Python e para que ela é usada?
serve para fazer looping até que atinge determinada informação que foi passada para parar o looping

2) Como você pode escrever uma estrutura de repetição simples usando a instrução while?

3) Qual é a diferença entre a instrução while e a instrução for em Python?

4) Como você pode evitar loops infinitos ao usar a instrução while?

5) O que são expressões booleanas e como elas são usadas com a instrução while?

6) Como você pode usar uma instrução while para iterar sobre uma lista em Python?

7) O que é uma condição de parada e como você pode usá-la com a instrução while?

8) Como você pode usar a instrução break para sair de um loop while prematuramente em Python?

9) O que é a instrução else em uma instrução while em Python e em que situações ela é útil?

10) Como você pode usar a instrução continue para pular uma iteração do loop while em Python?

11) O que são loops aninhados e como você pode usá-los com a instrução while?

12) Como você pode usar a instrução while para implementar lógica de repetição em um programa mais complexo?